### ISSUE TITLE
Not enough smiley faces

### ISSUE THREAD

**Issue by GirkovArpa** [MdderUofA/Lab-Net#1]
There are only 84 cool guy sunglasses dudes in the readme.  After careful examination and debugging I've determined there should be at least 85.

**Comment by MdderUofA** [comment]
Thank you for bringing this to my attention. I have cross checked your statements with professionals and they have confirmed that your examination is correct. the readme has been updated with additional sunglasses.
😎

**Comment by GirkovArpa** [comment]
Thank you for addressing this most pressing issue and putting my anxieties to rest.

**Comment by MdderUofA** [comment]
You are very welcome. Thanks to your heroic efforts to start the chain the coolness factor of our lab is at an all time high. We truly could not have done it without you.
Have an _extra cool_ day.
😎🤝😎
